server:
  port: 10002

# 数据源配置
spring:
  application:
    name: mc-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xu.123456
  redis:
    port: 6379
    host: 127.0.0.1
    password: xu.123456
    database: 0
    timeout: 10000



# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #mapper文件路径
  type-aliases-package: com.mc.common.entity #实体类路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    cache-enabled: true #开启二级缓存


security:
  oauth2:
    client:
      client-id: music-community
      client-secret: xu.123456
      grant-type:
        - password
        - refresh_token
      access-token-validity-seconds: 120
      refresh-token-validity-seconds: 600
      scope:
        - all
logging:
  level:
    spring: debug
